version: '2'
services:
  nginx:
    build: ./nginx
    image: hybridispeksi_nginx:0.1.1
    ports:
      - "80:80"
      - "443:443"
    networks:
      - docker-network
    links:
      - web
  web:
    build: .
    image: hybridispeksi_web:0.1.1
    ports:
      - "8080:8080"
    networks:
      docker-network:
        aliases:
          - web_1

networks:
  docker-network:
    driver: bridge
