version: '2'
services:
  web:
    build: .
    command: npm start
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:7007"
    environment:
      - NODE_ENV=production
      - PORT=7007
