version: '2'
services:
  nginx:
    image: pymapa/hybridispeksi_nginx:latest
    ports:
      - "80:80"
      - "443:443"
    networks:
      - docker-network
    links:
      - web
  web_1:
    image: pymapa/hybridispeksi_web:latest
    container_name: web_1
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - docker-network
  web_2:
    image: pymapa/hybridispeksi_web:latest
    container_name: web_2
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - docker-network

networks:
  docker-network:
    driver: bridge
