# Docker-compose for dev
version: '3'
services:
  front:
    build:
      context: ./
      dockerfile: ./dev/front.Dockerfile
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    links:
      - back:back
  back:
    build:
      context: ./
      dockerfile: ./dev/back.Dockerfile
    volumes:
      - ./:/app
    ports:
      - "8080:8080"
