# Docker-compose for dev
version: '3'
services:
  front:
    build:
      context: ./
      dockerfile: ./dev/front.Dockerfile
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    links:
      - back:back
  back:
    build:
      context: ./
      dockerfile: ./dev/back.Dockerfile
    volumes:
      - ./:/app
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/speksidev
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
      - ./config/my-postgres.conf:/etc/postgresql.conf
    command: postgres -c 'config_file=/etc/postgresql.conf'
  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@mail.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin
    volumes:
      - ./.pgadmindata/pgadmin:/root/.pgadmin
    ports:
      - "5050:80"
    restart: always
    restart: unless-stopped
    logging:
      driver: none
